stages:
    - run-pipeline

variables:
  PIPELINE_ACTION:
      value: ""
      description: run-integration-tests

deploy-aiw-ui-app-test:
  stage: run-pipeline
  rules:
      - if: $CI_PIPELINE_SOURCE == "push"
        when: manual
      - if: $CI_PIPELINE_SOURCE == "web"
        when: manual
  variables:
      ENVIRONMENT: test
  trigger:
      include: ./gitlab-ci/deploy.yml
      strategy: depend

deploy-aiw-ui-app-prod:
  stage: run-pipeline
  rules:
      - if: $CI_PIPELINE_SOURCE == "push"
        when: manual
      - if: $CI_PIPELINE_SOURCE == "web"
        when: manual
  variables:
      ENVIRONMENT: prod
  trigger:
      include: ./gitlab-ci/deploy.yml
      strategy: depend